# Generated by Django 4.1.1 on 2022-11-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_cart_menucategory_order_menuitem_cart_menu_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
