# Generated by Django 4.1.1 on 2022-11-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.IntegerField(null=True),
        ),
    ]
